name: Bump Patch Tag on Master

on:
    push:
        branches:
            - master

jobs:
    bump-patch:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0  # Necesario para obtener todos los tags

            - name: Set up Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Get latest tag and bump patch
              id: bump
              run: |
                  # Obtener el último tag (sin v)
                  latestTag=$(git tag --sort=-creatordate | head -n 1)

                  if [ -z "$latestTag" ]; then
                      newTag="0.0.1"
                  else
                      IFS='.' read -r major minor patch <<< "$latestTag"
                      patch=$((patch + 1))
                      newTag="$major.$minor.$patch"
                  fi

                  echo "✅ Nuevo tag: $newTag"
                  echo "new_tag=$newTag" >> "$GITHUB_OUTPUT"

            - name: Create and push tag
              run: |
                  git tag ${{ steps.bump.outputs.new_tag }}
                  git push origin ${{ steps.bump.outputs.new_tag }}
